### ISSUE TITLE
Investigate MemcachedKeyLengthError

### ISSUE THREAD

**Issue by cdrini** [cdrini/openlibrary#6]
Get this error a few times:
```
2019-05-14 00:12:34,377 [ERROR] failed to update work /works/OL16819403W
Traceback (most recent call last):
  File "openlibrary/solr/update_work.py", line 1156, in openlibrary.solr.update_work.update_work
    d = build_data(w)
  File "openlibrary/solr/update_work.py", line 689, in genexpr
    ia = dict((iaid, get_ia_collection_and_box_id(iaid)) for iaid in iaids)
  File "openlibrary/solr/update_work.py", line 689, in genexpr
    ia = dict((iaid, get_ia_collection_and_box_id(iaid)) for iaid in iaids)
  File "openlibrary/solr/update_work.py", line 99, in openlibrary.solr.update_work.get_ia_collection_and_box_id
    metadata = data_provider.get_metadata(ia)
  File "solr_builder_main.py", line 218, in solr_builder.solr_builder_main.LocalPostgresDataProvider.get_metadata
    return ia.get_metadata(identifier)
  File "/openlibrary/openlibrary/core/cache.py", line 102, in __call__
    value_time = self.memcache_get(args, kw)
  File "/openlibrary/openlibrary/core/cache.py", line 209, in memcache_get
    json = self.memcache.get(key)
  File "/usr/local/lib/python2.7/dist-packages/memcache.py", line 1121, in get
    return self._get('get', key)
  File "/usr/local/lib/python2.7/dist-packages/memcache.py", line 1065, in _get
    self.check_key(key)
  File "/usr/local/lib/python2.7/dist-packages/memcache.py", line 1316, in check_key
    "Key length is > %s" % self.server_max_key_length
MemcachedKeyLengthError: Key length is > 250
```

**Comment by cdrini** [comment]
This might be unrelated to this code; it looks like that editions has a garbage OCAID. https://openlibrary.org/books/OL25446137M/Beyblade_Volume_12

**Comment by cdrini** [comment]
Closing as one-off (reported to Jeff for fixing); will open an issue on openlibrary if I see more cases.
